# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yykPpmehM1F0mA-tGRXQRbXKcVRju99C
"""



print("hello worls")
x=10
y=20
print(x)

age=25
height='hello'
complex_num=3+4j
print(age)

"""INDENTATION MATTERS"""

if x>0:
  print("x is positive")
  print("this is inside block")

"""Boolean Type"""

is_active=True
is_active=False
print(is_active)

"""Type Checking"""

print(type(age))
print(type(height))

"""Type converstion"""

str_num="123"
int_num=int(str_num)

print(f"original:{str_num}(type:{type(str_num)})")

"""Personal information"""

first_name="hello"
second_name="he who"
print(f"{first_name} {second_name}")

"""Arithmetic operator"""

a=10
b=20
print(f"adition:{a}+{b}={a+b}")

age=int(input("enter a age"))
if age>35:
  print("you are promoted")

else:
  print("you not promote")
salary=int(input("enter a salary"))
if age>35 and salary>35000 :
  print("you are promoted")



else:
  print("you not promote")

"""sorting"""

student={"name":"a","age":1,"name":"b","age":2}
sorted_people=sorted(student,key=lambda age[2])

people = [
  {"name": "Alice", "age": 30},
  {"name": "Bob", "age": 25},
  {"name": "Charlie", "age": 35}
]

sorted_people = sorted(people, key=lambda person: person["age"])
print("People sorted by age:")

for person in sorted_people:
  print(f" {person['name']}: {person['age']}")